export const questions = [
  "Did you shower yesterday?",
  "Do you have dandruff in your hair?",
  "Do you say good morning at home?",
  "Do you think you're healthy?",
  "Do you talk about others behind their back?",
  "Do you pick your nose?",
  "Do you wash your hands after you pee?",
  "Do you pretend to like any of your friends?",
  "Have you ever walked in on your parents?",
  "Have you ever cheated on your partner?",
  "Does your underarm smell really bad?",
  "Have you ever committed a crime?",
  "Did you have a crush on your school teacher?",
  "Do you have bad breath?",
  "Do you have stinky feet?",
  "Do you chew with your mouth open and make loud noises?",
  "Have you ever stolen money from your parents?",
  "Do you take free samples at the supermarket?",
  "Do you get scared when the lights are off at night when you are alone at your home?",
  "Can you ride a bike?",
  "Have you ever done homework of others in exchange for something?",
  "Have you ever pooped in your pants after your 18?",
  "Have you ever asked a useless question in class and felt the judgement?",
  "If you smoked, would you smoke in front of others?",
  "Do you like pineapple pizza?",
  "Have you pretended to be sick at work to take a vacation?",
  "Have you ever recycled a gift?",
];
